### ISSUE TITLE
你好，移植Vue.js中，请教项目中的技术细节

### ISSUE THREAD

**Issue by roocky-one** [SabakiHQ/Shudan#10]
Sabaki是极好的项目，Shudan够美的棋盘，谢谢你这么好的作品。

我已用Vue.js重写了Shudan: https://github.com/roocky-lab/vue-shudan
中间有一些技术细节，请教一下：
-  Vertex.js: `shudan-random_${random}`，没有发现相关CSS，这是为什么功能预留？
- Goban.js: animate落子效果启用后，200ms后会取消，实现的目的是？
-  BoundedGoban.js: vertexSize这么计算的目的是？会否导致部分场景尺寸不正常？
   (比如Sabaki的Web版本，我Chrome 73.0.3683.86访问，初始棋盘尺寸极小，缩放窗口后正常）

@yishn

**Comment by yishn** [comment]
Thank you for the kind words! 

- The `.shudan-random_{n}` classes are for custom styling. For example if you have several images of a white stone (maybe with different patterns), you can use those classes to randomize your stone appearance. Shudan's default theme doesn't use it, but for example [this Sabaki theme does](https://github.com/geovens/Sabaki-Theme#wood-stone).
- `.shudan-animate` triggers the stone animation. You can try it out in the demo by activating 'Fuzzy stone placement' and 'Animate stone placement', and clicking on the board. You'll see that the stones will slide into place. After the animation is done, we remove the `.shudan-animate` class so animation cannot be triggered accidentally.
- In `BoundedGoban`, we want to calculate `vertexSize` from `maxWidth` and `maxHeight`, so the Goban component size won't exceed `maxWidth` and `maxHeight`. I can't reproduce the behavior you're describing in Sabaki Web; the board is the correct size without me needing to resize the window.

**Comment by roocky-one** [comment]
谢谢你的解答。

其中问题2，animate落子滑动效果，为什么要在一段时间(200ms)后取消呢？不取消有问题吗？

**Comment by yishn** [comment]
I don't remember the exact details... You can try it without removing `.shudan-animate` and see if you can encounter any issues.

On another note, please look at [the license for Shudan](https://github.com/SabakiHQ/Shudan/blob/master/LICENSE). Since you're using Shudan code in your project, you should adhere to its conditions: You have to have a copy of my license in your repository. Of course you can license your modifications under a different license.

**Comment by roocky-one** [comment]
你好，已添加[license文件](https://github.com/roocky-lab/vue-shudan/blob/master/LICENSE)，再次感谢这个项目。

关于shudan-animate是否延时关断，测试后并未发现区别。
